### ISSUE TITLE
Syntax error in isa_create_tour

### ISSUE THREAD

**Issue by ilveroluca** [phnmnl/container-galaxy-k8s-runtime#206]
There seems to be a syntax error in isa_create_tour.yaml.  When starting galaxy I get this exception:

```
galaxy.tours ERROR 2018-06-18 15:43:42,110 [p:59,w:0,m:0] [MainThread] Tour 'isa_create_tour' could not be loaded, error within file.  Please check your yaml syntax.
Traceback (most recent call last):
  File "lib/galaxy/tours/__init__.py", line 71, in _load_tour_from_path
    conf = yaml.safe_load(handle)
  File "/export/venv/local/lib/python2.7/site-packages/yaml/__init__.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "/export/venv/local/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/export/venv/local/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/export/venv/local/lib/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/export/venv/local/lib/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/export/venv/local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/export/venv/local/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/export/venv/local/lib/python2.7/site-packages/yaml/composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "/export/venv/local/lib/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/export/venv/local/lib/python2.7/site-packages/yaml/parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "/export/venv/local/lib/python2.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/export/venv/local/lib/python2.7/site-packages/yaml/scanner.py", line 257, in fetch_more_tokens
    % ch.encode('utf-8'), self.get_mark())
ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "lib/galaxy/util/../../.././config/plugins/tours/isa_create_tour.yaml", line 7, column 1
```

**Comment by ilveroluca** [comment]
Solved by PR #242
