### ISSUE TITLE
ISA get data files broken for MTBLS36

### ISSUE THREAD

**Issue by sneumann** [phnmnl/container-galaxy-k8s-runtime#292]
Hi @djcomlab ,
If I run https://publicdev.phenomenal-h2020.eu/?tool_id=isa_get_data_files_list 
and provide the `MetaboLights Study Identifier` MTBLS36, then I get:
```
2018-07-24T10:07:26.554175771Z 2018-07-24 10:07:26,553 [INFO]: isaslicer.py(get_data_files_command:477) >> Getting data files for study MTBLS36. Writing to /export/galaxy-central/database/files/005/dataset_5112.dat.
2018-07-24T10:07:26.694010073Z 2018-07-24 10:07:26,690 [ERROR]: isaslicer.py(<module>:1263) >> invalid syntax (<unknown>, line 1)
2018-07-24T10:07:26.694037738Z Traceback (most recent call last):
2018-07-24T10:07:26.694041605Z   File "/usr/local/bin/isaslicer.py", line 1260, in <module>
2018-07-24T10:07:26.69404536Z     main(sys.argv[1:])
2018-07-24T10:07:26.694048296Z   File "/usr/local/bin/isaslicer.py", line 1255, in main
2018-07-24T10:07:26.694051692Z     options.func(options)
2018-07-24T10:07:26.694054892Z   File "/usr/local/bin/isaslicer.py", line 490, in get_data_files_command
2018-07-24T10:07:26.694057938Z     data_files = MTBLS.get_data_files(options.study_id, json_struct)
2018-07-24T10:07:26.694060822Z   File "/usr/lib/python3.6/site-packages/isatools/net/mtbls.py", line 161, in get_data_files
2018-07-24T10:07:26.694063874Z     result = slice_data_files(tmp_dir, factor_selection=factor_selection)
2018-07-24T10:07:26.694066755Z   File "/usr/lib/python3.6/site-packages/isatools/net/mtbls.py", line 228, in slice_data_files
2018-07-24T10:07:26.694069781Z     query_results = df.query(factor_query)[
2018-07-24T10:07:26.694072825Z   File "/usr/lib/python3.6/site-packages/pandas/core/frame.py", line 2116, in query
2018-07-24T10:07:26.69407583Z     res = self.eval(expr, **kwargs)
2018-07-24T10:07:26.694078543Z   File "/usr/lib/python3.6/site-packages/pandas/core/frame.py", line 2186, in eval
2018-07-24T10:07:26.694081537Z     return _eval(expr, inplace=inplace, **kwargs)
2018-07-24T10:07:26.69408421Z   File "/usr/lib/python3.6/site-packages/pandas/core/computation/eval.py", line 262, in eval
2018-07-24T10:07:26.694087181Z     truediv=truediv)
2018-07-24T10:07:26.694089839Z   File "/usr/lib/python3.6/site-packages/pandas/core/computation/expr.py", line 727, in __init__
2018-07-24T10:07:26.694092756Z     self.terms = self.parse()
2018-07-24T10:07:26.694095371Z   File "/usr/lib/python3.6/site-packages/pandas/core/computation/expr.py", line 744, in parse
2018-07-24T10:07:26.694098686Z     return self._visitor.visit(self.expr)
2018-07-24T10:07:26.694101409Z   File "/usr/lib/python3.6/site-packages/pandas/core/computation/expr.py", line 309, in visit
2018-07-24T10:07:26.69410433Z     node = ast.fix_missing_locations(ast.parse(clean))
2018-07-24T10:07:26.694107033Z   File "/usr/lib/python3.6/ast.py", line 35, in parse
2018-07-24T10:07:26.694109867Z     return compile(source, filename, mode, PyCF_ONLY_AST)
2018-07-24T10:07:26.69411257Z   File "<unknown>", line 1
2018-07-24T10:07:26.694117007Z     ==""
2018-07-24T10:07:26.694119731Z      ^
2018-07-24T10:07:26.694122341Z SyntaxError: invalid syntax
2018-07-24T10:07:26.694131793Z 2018-07-24 10:07:26,693 [ERROR]: isaslicer.py(<module>:1264) >> invalid syntax (<unknown>, line 1)
```
Yours, 
Steffen

**Comment by djcomlab** [comment]
Removing this tool in favour of `ISAslicer2`.
