### ISSUE TITLE
Error in `msconvert2` wrapper help

### ISSUE THREAD

**Issue by ilveroluca** [phnmnl/container-galaxy-k8s-runtime#313]
```galaxy.tools ERROR 2018-07-31 16:44:04,664 [p:59,w:0,m:0] [MainThread] Exception while parsing help for tool with id 'msconvert2'
Traceback (most recent call last):
  File "lib/galaxy/tools/__init__.py", line 1156, in __inititalize_help
    self.__help = Template(rst_to_html(help_text), input_encoding='utf-8',
  File "lib/galaxy/util/__init__.py", line 799, in rst_to_html
    settings_overrides=settings_overrides))
  File "/export/venv/local/lib/python2.7/site-packages/docutils/core.py", line 416, in publish_string
    enable_exit_status=enable_exit_status)
  File "/export/venv/local/lib/python2.7/site-packages/docutils/core.py", line 664, in publish_programmatically
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/export/venv/local/lib/python2.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/export/venv/local/lib/python2.7/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/export/venv/local/lib/python2.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/export/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/__init__.py", line 191, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/export/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/export/venv/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/export/venv/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/export/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 1150, in indent
    elements = self.block_quote(indented, line_offset)
  File "/export/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 1165, in block_quote
    self.nested_parse(blockquote_lines, line_offset, blockquote)
  File "/export/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/export/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/export/venv/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/export/venv/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/export/venv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2398, in line
    line=self.state_machine.abs_line_number())
  File "/export/venv/local/lib/python2.7/site-packages/docutils/utils/__init__.py", line 236, in severe
    return self.system_message(self.SEVERE_LEVEL, *args, **kwargs)
  File "/export/venv/local/lib/python2.7/site-packages/docutils/utils/__init__.py", line 194, in system_message
    raise SystemMessage(msg, level)
SystemMessage: <string>:6: (SEVERE/4) Unexpected section title or transition.

```

**Comment by ilveroluca** [comment]
wait...I just saw the PR waiting to be approved.  I'll try again :-)
