### ISSUE TITLE
Catch "public name is used" in user set up

### ISSUE THREAD

**Issue by pcm32** [phnmnl/container-galaxy-k8s-runtime#41]
When trying to setup an admin user and there are existing settings available, a collision of the public name for the admin user makes the process fail:

```
.......[ run_galaxy_config.sh ] -- Galaxy is up and ready for API calls after 7 seconds.
[ run_galaxy_config.sh ] -- Running admin user creation...
[ run_galaxy_config.sh ] -- Workflow directory: ./workflows
DEBUG	[ ConfigGalaxy ]	Galaxy config running from /galaxy
INFO	[ ConfigGalaxy ]	Configuring admin user
DEBUG	[ bioblend ]	GET - attempts left: 1; retry delay: 10
INFO	[ requests.packages.urllib3.connectionpool ]	Starting new HTTP connection (1): 127.0.0.1
DEBUG	[ requests.packages.urllib3.connectionpool ]	"GET /api/users?key=qwertyuio HTTP/1.1" 200 None
INFO	[ requests.packages.urllib3.connectionpool ]	Starting new HTTP connection (1): 127.0.0.1
DEBUG	[ requests.packages.urllib3.connectionpool ]	"POST /api/users?key=qwertyuio HTTP/1.1" 400 None
Traceback (most recent call last):
  File "ansible/configure_galaxy.py", line 166, in <module>
    main(sys.argv[1:])
  File "ansible/configure_galaxy.py", line 151, in main
    admin_user = configure_admin_user(options)
  File "ansible/configure_galaxy.py", line 140, in configure_admin_user
    admin_user = gi.users.create_local_user(options.username, options.user_email, options.user_password)
  File "/galaxy/.venv/local/lib/python2.7/site-packages/bioblend/galaxy/users/__init__.py", line 103, in create_local_user
    return Client._post(self, payload)
  File "/galaxy/.venv/local/lib/python2.7/site-packages/bioblend/galaxy/client.py", line 171, in _post
    files_attached=files_attached)
  File "/galaxy/.venv/local/lib/python2.7/site-packages/bioblend/galaxyclient.py", line 131, in make_post_request
    r.status_code, body=r.text)
bioblend.galaxy.client.ConnectionError: Unexpected response from galaxy: 400: {"err_msg": "\n\nPublic name is taken; please choose another.", "err_code": 400008}
[ run_galaxy_config.sh ] -- CITATION CODE_OF_CONDUCT.md CONTRIBUTING.md CONTRIBUTORS.md LICENSE.txt Makefile README.rst ansible client config config_db.log container-simple-checks.sh contrib create_db.sh cron database display_applications doc external_service_types extract_dataset_parts.sh integrated_tool_panel.xml lib locale manage_db.sh manage_tools.sh openid paster.log paster.pid requirements.txt rolling_restart.sh run.sh run_reports.sh run_tests.sh run_tool_shed.sh scripts setup.cfg static templates test test-data test_cmds.txt tool-data tool_list.py tools tox.ini workflows Error at line 86 running command python ansible/configure_galaxy.py --workflow-dir "${WorkflowDir}" $GALAXY_API_KEY $GALAXY_ADMIN_USER $GALAXY_ADMIN_EMAIL $GALAXY_ADMIN_PASSWORD 1>&2 CITATION CODE_OF_CONDUCT.md CONTRIBUTING.md CONTRIBUTORS.md LICENSE.txt Makefile README.rst ansible client config config_db.log container-simple-checks.sh contrib create_db.sh cron database display_applications doc external_service_types extract_dataset_parts.sh integrated_tool_panel.xml lib locale manage_db.sh manage_tools.sh openid paster.log paster.pid requirements.txt rolling_restart.sh run.sh run_reports.sh run_tests.sh run_tool_shed.sh scripts setup.cfg static templates test test-data test_cmds.txt tool-data tool_list.py tools tox.ini workflows
```

Maybe we need to be able to either recover from the error or have a very explicit message telling the admin to make the helm install call with a different `galaxy_admin_user`. What do you think @ilveroluca ?

**Comment by ilveroluca** [comment]
I think the only plausible recovery would be to leave the existing admin user account, and make sure the user sees this happened (he might have a different password and be unable to log in).

The error solution would be safer, I think.  For robustness in automation, we could maybe add an option to force the creation of the user account, even if it means overriding/deleting a previously existing conflicting account.

I'd vote for the second one.

**Comment by ilveroluca** [comment]
I think this was solved a while ago.
