### ISSUE TITLE
At some point, log running instances run out of connections to k8s

### ISSUE THREAD

**Issue by pcm32** [phnmnl/container-galaxy-k8s-runtime#48]
Found this on our public instance, after 14 days running and 2 restarts of the pod...

```
galaxy.jobs.runners ERROR 2017-07-07 14:17:37,467 (4754) Unhandled exception calling queue_job
Traceback (most recent call last):
  File "/galaxy/lib/galaxy/jobs/runners/__init__.py", line 104, in run_next
    method(arg)
  File "/galaxy/lib/galaxy/jobs/runners/kubernetes.py", line 107, in queue_job
    if job.exists():
  File "/galaxy/.venv/local/lib/python2.7/site-packages/pykube/objects.py", line 85, in exists
    r = self.api.get(**self.api_kwargs())
  File "/galaxy/.venv/local/lib/python2.7/site-packages/pykube/http.py", line 127, in get
    return self.session.get(*args, **self.get_kwargs(**kwargs))
  File "/galaxy/.venv/local/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/galaxy/.venv/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/galaxy/.venv/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/galaxy/.venv/local/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='kubernetes', port=443): Max retries exceeded with url: /apis/batch/v1/namespaces/default/jobs/galaxy-4754 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe5bd39f750>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

I have seen other instances running for much longer without this error. Maybe is related to the load of the instance.

**Comment by pcm32** [comment]
Tried restarting kubelet and proxy on the running node, but made no difference. There seemed to a be a kubedns pod failing on one of the master nodes, so I restarted that master and that sorted this out.

**Comment by pcm32** [comment]
I saw this error again. This time I noticed that kube-dns was having issues:

```
$ kubectl get pods --namespace=kube-system
kubedns-tf6zz                              3/4       CrashLoopBackOff   15756      283d
```

There wasn't any clue to understand why kube2sky was constantly failing, but `kubectl delete pods/kubedns-tf6zz` provided with a working pod again, and then the max error connection went away.

**Comment by pcm32** [comment]
@jianlianggao this is what explains the "hanged" error that you have reported some times. Please let me know when you see this behaviour again.
